### ISSUE TITLE
Add entry/entries for EchoPro and Hake-IGP projects

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/group-website#26]
They could be combined into a single project description, maybe.

https://github.com/uw-echospace/group-website/tree/main/content/project

**Comment by emiliom** [comment]
Paragraphs taken from the CICOES proposal abstracts.

## Hake IGP project

Conventional acoustic surveys utilize biological data collected with temporally and spatially co-located midwater and/or bottom trawls to validate their observations, i.e., acoustic-trawl (AT) data. To take advantage of the recent technological advances in collecting acoustic data via platforms different from the traditional ship-based systems, such as uncrewed marine systems (UxSs), we need to seek alternative strategies that can provide crucial biological information. We propose exploring the applicability of using biological information for Pacific hake from bottom trawl (BT) surveys and the at-sea hake observer programs (OP) in both U.S. and Canadian waters to augment coast-wide hake acoustic surveys using UxSs. In addition, we propose integrating the AT, BT, and OP biological data from 2003 to 2019 into a NWFSC-hosted database with a unified format. We should then be able to quantitatively evaluate similarities and differences among the three data sources and assess the associated variability. The software package developed by the UW team will allow integrating all three data sources into a unified forma and allow research to answer two important questions: (1) Can we use biological data from alternative sources to provide effective and satisfactory biomass estimates or biomass indices for UMS acoustic surveys? (2) Can we extract new biological information on hake by analyzing the integrated fishery–dependent (OP) and fishery–independent (AT and BT) data? 

## EchoPro Modernization / Conversion

The Fisheries Engineering and Acoustic Technologies (FEAT) Team at NWFSC and their collaborators in DFO Canada need to complete analyses to estimate total biomass of Pacific hake in an efficient and timely manner by incorporating acoustic and biological trawl data from the Joint US and Canada Pacific Hake Acoustic Trawl Surveys. These biomass estimates are the inputs for the stock assessment of hake. The biomass estimates are currently produced by a suite of Matlab scripts operated by a single user, and the analysis procedures are not easily adaptable by other FEAT/DFO team members. The central objective of this project is to provide a well-documented open-source Python software package that contains the core computational functionality of the current Matlab EchoPro program and provides basic visualization capability of the analysis results. The new software package will contain an Application Programming Interface (API) that can be invoked in a reproducible manner and can accept configuration of key analysis parameters and other run-time setups via a machine and human-readable configuration file.

**Comment by leewujung** [comment]
Addressed by #38.

**Comment by emiliom** [comment]
Woo-hoo!
