### ISSUE TITLE
Add presentation widget, and 2 recent presentations

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/group-website#27]
(creating an issue so it's a bit easier to keep track of this)

From @leewujung:

> there’s actually a specific “presentation” widget type for talks that i used for my personal site, i didn’t bother with it when worked on this site. Perhaps it’s now time to revive that section.
> I’ll also look to see if there’s one that can repurposed into a News section

Once that's in place I'll add my IOOS DMAC presentation; and you can add your eScience presentation from a month ago.

**Comment by leewujung** [comment]
Addressed by #34.
