### ISSUE TITLE
Add presentation from NCEI WCSD Archive 2022 workshop

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/group-website#42]
Trying again, now in the right repo ...

**Comment by leewujung** [comment]
@emiliom : I assume that this is both an entry for the talk and the slides, right?

**Comment by emiliom** [comment]
That's my thought. Too bad we didn't have an abstract. But we can just write a couple of sentences. I can volunteer to do that if you'd like, to spread the work.

**Comment by leewujung** [comment]
Sounds good! How about I PR the entry and slides and you add to the PR?
